### PR TITLE
added text to readme

### PR DESCRIPTION
**Pull request by julianlam**

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled via [Transifex](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

**Comment by julianlam** [comment]
... and close!

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled via [Transifex](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled via [Transifex](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled via [Transifex](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

**Pull request closed without merging**
